### ISSUE TITLE
Solve gripper loss

### ISSUE THREAD

**Issue by sholtodouglas** [sholtodouglas/learning_from_play#7]
Huber loss at small magnitudes is too smooth for the gripper, leading to directionally correct but not sharp enough behaviour.

**Comment by 0xtristan** [comment]
Added gripper weighting term since gripper values are [0,0.04] whereas other states are [0,0.2]. Gripper dim currently underfits heaps so this should prioritise learning this state. Changing to MAE loss seems to have also helped this (because before MSE loss underweighted the gripper even more).
